# Generated by Django 3.2.7 on 2021-09-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_name', models.CharField(max_length=128)),
                ('next_trigger_time', models.BigIntegerField()),
                ('create_time', models.BigIntegerField(default=1632683381378)),
                ('update_time', models.BigIntegerField(default=1632683381378)),
                ('remark', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('description', models.TextField()),
                ('ip_address', models.CharField(max_length=15)),
                ('healthy', models.BooleanField(default=False)),
                ('create_time', models.BigIntegerField(default=1632683381379)),
            ],
        ),
    ]
